/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jjm_view;

import bean.JjmProdutos;
import dao.ProdutosDAO;
import dao.UsuariosDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import tools.Util;

/**
 *
 * @author user
 */
public class Jjm_JDlgProdutos extends javax.swing.JDialog {

    /**
     * Creates new form Jjm_JDlgProdutos
     */ private boolean incluir; 
        boolean pesquisando = false;
            private MaskFormatter mascaraCpf, mascaraDataNasc;


    public Jjm_JDlgProdutos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);

           jjm_jBtnConfirmar.setEnabled(false);
        jjm_jBtnCancelar.setEnabled(false);

       
        Util.habilitar(false, jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);
    
          try {
            mascaraDataNasc = new MaskFormatter("##/##/####");
            jjm_jFmtDatadecadastro.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNasc));
        } catch (ParseException ex) {
            Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
public JjmProdutos viewBean() {
    JjmProdutos jjmProdutos = new JjmProdutos();

    jjmProdutos.setJjmIdProduto(Util.strToInt(jjm_jTxtProduto.getText()));
    jjmProdutos.setJjmNome(jjm_jTxtNome.getText());
    jjmProdutos.setJjmDescricao(jjm_jTxtDescricao.getText());
    jjmProdutos.setJjmPreco(Util.strToDuble(jjm_jTxtPreco.getText()));
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
 try {
                    Date dataNasc = formato.parse(jjm_jFmtDatadecadastro.getText());
                    jjmProdutos.setJjmDataCadastro(dataNasc);
                } catch (ParseException ex) {
                    Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(Level.SEVERE, null, ex);
                }
    jjmProdutos.setJjmMarca(jjm_jTxtMarca.getText());
    jjmProdutos.setJjmCategoria(jjm_jTxtCategoria.getText());

    return jjmProdutos;
}

public void beanView(JjmProdutos jjmProdutos) {
    jjm_jTxtProduto.setText(Util.intToStr(jjmProdutos.getJjmIdProduto()));
    jjm_jTxtNome.setText(jjmProdutos.getJjmNome());
    jjm_jTxtDescricao.setText(jjmProdutos.getJjmDescricao());
    jjm_jTxtPreco.setText(Util.doubleToStr(jjmProdutos.getJjmPreco()));
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
                String dataNasc = formato.format(jjmProdutos.getJjmDataCadastro());
                jjm_jFmtDatadecadastro.setText(dataNasc);
    jjm_jTxtMarca.setText(jjmProdutos.getJjmMarca());
    jjm_jTxtCategoria.setText(jjmProdutos.getJjmCategoria());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjm_jLblPreco = new javax.swing.JLabel();
        jjm_jLblProduto = new javax.swing.JLabel();
        jjm_jTxtProduto = new javax.swing.JTextField();
        jjm_jLblNome = new javax.swing.JLabel();
        jjm_jTxtNome = new javax.swing.JTextField();
        jjm_jLblDescricao = new javax.swing.JLabel();
        jjm_jTxtDescricao = new javax.swing.JTextField();
        jjm_jLblPreco1 = new javax.swing.JLabel();
        jjm_jTxtPreco = new javax.swing.JTextField();
        jjm_jLblDataDeCadrastro = new javax.swing.JLabel();
        jjm_jFmtDatadecadastro = new javax.swing.JFormattedTextField();
        jjm_jLblMarca = new javax.swing.JLabel();
        jjm_jTxtMarca = new javax.swing.JTextField();
        jjm_jLblCategoria = new javax.swing.JLabel();
        jjm_jTxtCategoria = new javax.swing.JTextField();
        jjm_jBtnIncluir = new javax.swing.JButton();
        jjm_jBtnExcluir = new javax.swing.JButton();
        jjm_jBtnConfirmar = new javax.swing.JButton();
        jjm_jBtnPesquisar = new javax.swing.JButton();
        jjm_jBtnAlterar = new javax.swing.JButton();
        jjm_jBtnCancelar = new javax.swing.JButton();

        jjm_jLblPreco.setText("Preco");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jjm_jLblProduto.setText("Produto:");

        jjm_jTxtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jTxtProdutoActionPerformed(evt);
            }
        });

        jjm_jLblNome.setText("Nome:");

        jjm_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jTxtNomeActionPerformed(evt);
            }
        });

        jjm_jLblDescricao.setText("Descricao");

        jjm_jLblPreco1.setText("Preco");

        jjm_jLblDataDeCadrastro.setText("Data De Cadastro");

        jjm_jLblMarca.setText("Marca");

        jjm_jLblCategoria.setText("Categoria");

        jjm_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jjm_jBtnIncluir.setText("Incluir");
        jjm_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnIncluirActionPerformed(evt);
            }
        });

        jjm_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jjm_jBtnExcluir.setText("Excluir");
        jjm_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnExcluirActionPerformed(evt);
            }
        });

        jjm_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jjm_jBtnConfirmar.setText("Confirmar");
        jjm_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnConfirmarActionPerformed(evt);
            }
        });

        jjm_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jjm_jBtnPesquisar.setText("Pesquisar");
        jjm_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnPesquisarActionPerformed(evt);
            }
        });

        jjm_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jjm_jBtnAlterar.setText("Alterar");
        jjm_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnAlterarActionPerformed(evt);
            }
        });

        jjm_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jjm_jBtnCancelar.setText("Cancelar");
        jjm_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jLblProduto)
                        .addGap(71, 71, 71)
                        .addComponent(jjm_jLblNome)
                        .addGap(78, 78, 78)
                        .addComponent(jjm_jLblDescricao))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjm_jTxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjm_jLblPreco1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjm_jLblDataDeCadrastro))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jjm_jLblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jjm_jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jjm_jLblCategoria)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jjm_jTxtCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(jjm_jTxtPreco, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jFmtDatadecadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jjm_jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jBtnIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jBtnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jBtnAlterar)))
                .addGap(0, 48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jjm_jBtnExcluir)
                .addGap(18, 18, 18)
                .addComponent(jjm_jBtnPesquisar)
                .addGap(18, 18, 18)
                .addComponent(jjm_jBtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jjm_jLblProduto)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jjm_jLblNome)
                            .addComponent(jjm_jLblDescricao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblPreco1)
                    .addComponent(jjm_jLblDataDeCadrastro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jLblMarca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jFmtDatadecadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jjm_jLblCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jjm_jTxtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnIncluir)
                    .addComponent(jjm_jBtnConfirmar)
                    .addComponent(jjm_jBtnAlterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnExcluir)
                    .addComponent(jjm_jBtnPesquisar)
                    .addComponent(jjm_jBtnCancelar))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jjm_jTxtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jTxtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jTxtProdutoActionPerformed

    private void jjm_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jTxtNomeActionPerformed

    private void jjm_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);

        Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);
        Util.habilitar(true, jjm_jBtnConfirmar, jjm_jBtnCancelar);

        Util.limpar(jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);
        incluir=true;
        jjm_jTxtProduto.grabFocus();
    }//GEN-LAST:event_jjm_jBtnIncluirActionPerformed

    private void jjm_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnExcluirActionPerformed
    
    if (pesquisando == false) {
            Util.mensagem("Você precisa pesquisar um usuário primeiro");
        } else {
                Util.perguntar("Você deseja excluir?");
                Util.limpar(jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);  
        }
    }//GEN-LAST:event_jjm_jBtnExcluirActionPerformed

    private void jjm_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnConfirmarActionPerformed
 ProdutosDAO produtosDAO = new ProdutosDAO();
        if (incluir == true) {
            produtosDAO.insert(viewBean());
        } else {
            produtosDAO.update(viewBean());
        }
        Util.habilitar(false, jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);

        Util.habilitar(true, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);
        Util.habilitar(false, jjm_jBtnConfirmar, jjm_jBtnCancelar);
        Util.limpar(jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);
          
    }//GEN-LAST:event_jjm_jBtnConfirmarActionPerformed

    private void jjm_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        /*String id = JOptionPane.showInputDialog(null, "Entre com o código ?");
        int codigo = Integer.valueOf(id);
        Jjm_ProdutoDAO produtoDAO = new Jjm_ProdutoDAO();
        Jjm_Produto produto = (Jjm_Produto) produtoDAO.list(codigo);
        if (produto == null) {
            JOptionPane.showMessageDialog(null, "Codigo nao existente");
        } else {
            jjm_jTxtProduto.setText(id);
            jjm_jTxtNome.setText(produto.getjjm_Nome());
            jjm_jTxtDescricao.setText(produto.getjjm_Descricao());
            jjm_jTxtPreco.setText(produto.getjjm_Preco());
            jjm_jFmtDatadecadastro.setText(null);
            jjm_jTxtMarca.setText(produto.getjjm_Marca());
            jjm_jTxtCategoria.setText(produto.getjjm_Categoria());

        }*/
       JDlgProdutoPesquisar jDlgProdutoPesquisar = new JDlgProdutoPesquisar(null, true);
        jDlgProdutoPesquisar.setTelaPai(this);
        jDlgProdutoPesquisar.setVisible(true);
        pesquisando = true;
        
      
    }//GEN-LAST:event_jjm_jBtnPesquisarActionPerformed

    private void jjm_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnAlterarActionPerformed
 Util.habilitar(true, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);

        Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);
        Util.habilitar(true, jjm_jBtnConfirmar, jjm_jBtnCancelar);
            incluir=false;
            jjm_jTxtNome.grabFocus();
    }//GEN-LAST:event_jjm_jBtnAlterarActionPerformed

    private void jjm_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnCancelarActionPerformed
 Util.habilitar(false, jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);

        Util.habilitar(true, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);
        Util.habilitar(false, jjm_jBtnConfirmar, jjm_jBtnCancelar);
        Util.limpar(jjm_jTxtProduto, jjm_jTxtNome, jjm_jTxtDescricao,
                jjm_jTxtPreco, jjm_jFmtDatadecadastro, jjm_jTxtMarca, jjm_jTxtCategoria);
           
    }//GEN-LAST:event_jjm_jBtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jjm_JDlgProdutos dialog = new Jjm_JDlgProdutos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jjm_jBtnAlterar;
    private javax.swing.JButton jjm_jBtnCancelar;
    private javax.swing.JButton jjm_jBtnConfirmar;
    private javax.swing.JButton jjm_jBtnExcluir;
    private javax.swing.JButton jjm_jBtnIncluir;
    private javax.swing.JButton jjm_jBtnPesquisar;
    private javax.swing.JFormattedTextField jjm_jFmtDatadecadastro;
    private javax.swing.JLabel jjm_jLblCategoria;
    private javax.swing.JLabel jjm_jLblDataDeCadrastro;
    private javax.swing.JLabel jjm_jLblDescricao;
    private javax.swing.JLabel jjm_jLblMarca;
    private javax.swing.JLabel jjm_jLblNome;
    private javax.swing.JLabel jjm_jLblPreco;
    private javax.swing.JLabel jjm_jLblPreco1;
    private javax.swing.JLabel jjm_jLblProduto;
    private javax.swing.JTextField jjm_jTxtCategoria;
    private javax.swing.JTextField jjm_jTxtDescricao;
    private javax.swing.JTextField jjm_jTxtMarca;
    private javax.swing.JTextField jjm_jTxtNome;
    private javax.swing.JTextField jjm_jTxtPreco;
    private javax.swing.JTextField jjm_jTxtProduto;
    // End of variables declaration//GEN-END:variables
}
