/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jjm_view;

import bean.JjmVendedor;
import dao.VendedorDAO;
import tools.Util;

/**
 *
 * @author user
 */
public class Jjm_JDlgVendedor extends javax.swing.JDialog {

    /**
     * Creates new form Jjm_JDlgVendedor
     */
     boolean pesquisando = false;
        private boolean incluir; 


    public Jjm_JDlgVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         Util.habilitar(false, jjm_jTxtVendedor, jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco);

   
    Util.habilitar(false, jjm_jBtnConfirmar, jjm_jBtnCancelar);

 
    Util.habilitar(true, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

    }
    public JjmVendedor viewBean() {
    JjmVendedor jjmVendedor = new JjmVendedor();
    jjmVendedor.setJjmIdVendedor(Util.strToInt(jjm_jTxtVendedor.getText()));
    jjmVendedor.setJjmNome(jjm_jTxtNome.getText());
    jjmVendedor.setJjmEmail(jjm_jTxtEmail.getText());
    jjmVendedor.setJjmTelefone(jjm_jTxtTelefone.getText());
    jjmVendedor.setJjmDataCadrastro(Util.strToDate(jjm_jFmtDatadecadastro.getText()));
    jjmVendedor.setJjmSalario(Util.strToDuble(jjm_jTxtSalario.getText()));
    jjmVendedor.setJjmEndereco(jjm_jTxtEndereco.getText());
    return jjmVendedor;
}

public void beanView(JjmVendedor jjmVendedor) {
    jjm_jTxtVendedor.setText(Util.intToStr(jjmVendedor.getJjmIdVendedor()));
    jjm_jTxtNome.setText(jjmVendedor.getJjmNome());
    jjm_jTxtEmail.setText(jjmVendedor.getJjmEmail());
    jjm_jTxtTelefone.setText(jjmVendedor.getJjmTelefone());
    jjm_jFmtDatadecadastro.setText(Util.dateToStr(jjmVendedor.getJjmDataCadrastro()));
    jjm_jTxtSalario.setText(Util.doubleToStr(jjmVendedor.getJjmSalario()));
    jjm_jTxtEndereco.setText(jjmVendedor.getJjmEndereco());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjm_jTxtTelefone = new javax.swing.JTextField();
        jjm_jLblDataDeCadrastro = new javax.swing.JLabel();
        jjm_jFmtDatadecadastro = new javax.swing.JFormattedTextField();
        jjm_jLblSalario = new javax.swing.JLabel();
        jjm_jTxtSalario = new javax.swing.JTextField();
        jjm_jLblVendedor = new javax.swing.JLabel();
        jjm_jLblEndereco = new javax.swing.JLabel();
        jjm_jTxtVendedor = new javax.swing.JTextField();
        jjm_jTxtEndereco = new javax.swing.JTextField();
        jjm_jLblNome = new javax.swing.JLabel();
        jjm_jTxtNome = new javax.swing.JTextField();
        jjm_jLblEmail = new javax.swing.JLabel();
        jjm_jTxtEmail = new javax.swing.JTextField();
        jjm_jLblTelefone = new javax.swing.JLabel();
        jjm_jBtnCancelar = new javax.swing.JButton();
        jjm_jBtnPesquisar = new javax.swing.JButton();
        jjm_jBtnIncluir = new javax.swing.JButton();
        jjm_jBtnAlterar = new javax.swing.JButton();
        jjm_jBtnExcluir = new javax.swing.JButton();
        jjm_jBtnConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jjm_jLblDataDeCadrastro.setText("Data De Cadrastro");

        jjm_jLblSalario.setText("Salario");

        jjm_jLblVendedor.setText("Vendedor");

        jjm_jLblEndereco.setText("Endereco");

        jjm_jLblNome.setText("Nome:");

        jjm_jLblEmail.setText("Email:");

        jjm_jLblTelefone.setText("Telefone");

        jjm_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jjm_jBtnCancelar.setText("Cancelar");
        jjm_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnCancelarActionPerformed(evt);
            }
        });

        jjm_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jjm_jBtnPesquisar.setText("Pesquisar");
        jjm_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnPesquisarActionPerformed(evt);
            }
        });

        jjm_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jjm_jBtnIncluir.setText("Incluir");
        jjm_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnIncluirActionPerformed(evt);
            }
        });

        jjm_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jjm_jBtnAlterar.setText("Alterar");
        jjm_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnAlterarActionPerformed(evt);
            }
        });

        jjm_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jjm_jBtnExcluir.setText("Excluir");
        jjm_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnExcluirActionPerformed(evt);
            }
        });

        jjm_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jjm_jBtnConfirmar.setText("Confirmar");
        jjm_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jLblVendedor)
                        .addGap(75, 75, 75)
                        .addComponent(jjm_jLblNome)
                        .addGap(88, 88, 88)
                        .addComponent(jjm_jLblEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jjm_jTxtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jjm_jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjm_jLblTelefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jjm_jLblDataDeCadrastro)
                                    .addComponent(jjm_jFmtDatadecadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jjm_jLblSalario)
                            .addComponent(jjm_jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jjm_jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jjm_jLblEndereco)
                    .addComponent(jjm_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jBtnExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jBtnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jjm_jBtnCancelar)))
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jjm_jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jjm_jBtnConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jjm_jBtnAlterar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblVendedor)
                    .addComponent(jjm_jLblNome)
                    .addComponent(jjm_jLblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblTelefone)
                    .addComponent(jjm_jLblDataDeCadrastro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jLblSalario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jFmtDatadecadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jjm_jLblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jjm_jTxtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnIncluir)
                    .addComponent(jjm_jBtnConfirmar)
                    .addComponent(jjm_jBtnAlterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnExcluir)
                    .addComponent(jjm_jBtnPesquisar)
                    .addComponent(jjm_jBtnCancelar))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jjm_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnCancelarActionPerformed
      Util.habilitar(false, jjm_jTxtVendedor, jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco,
            jjm_jBtnConfirmar, jjm_jBtnCancelar);
    
    Util.habilitar(true, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar, jjm_jBtnIncluir);
    }//GEN-LAST:event_jjm_jBtnCancelarActionPerformed

    private void jjm_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        /*
        String id = JOptionPane.showInputDialog(null, "Entre com o código ?");
        int codigo = Integer.valueOf(id);
        Jjm_VendedorDAO vendedorDAO = new Jjm_VendedorDAO();
        Jjm_Vendedor vendedor = (Jjm_Vendedor) vendedorDAO.list(codigo);
        if (vendedor == null) {
            JOptionPane.showMessageDialog(null, "Codigo nao existente");
        } else {
            jjm_jTxtVendedor.setText(id);
            jjm_jTxtNome.setText(vendedor.getjjm_Nome());
            jjm_jTxtEmail.setText(vendedor.getjjm_Email());
            jjm_jTxtTelefone.setText(vendedor.getjjm_Telefone());
            jjm_jFmtDatadecadastro.setText(null);
            jjm_jTxtSalario.setText(vendedor.getjjm_Salario());
            jjm_jTxtEndereco.setText(vendedor.getjjm_Endereco());

        }
        */
        JDlgVendedorPesquisar jDlgVendedorPesquisar = new JDlgVendedorPesquisar(null, true);
        jDlgVendedorPesquisar.setTelaPai(this);
        jDlgVendedorPesquisar.setVisible(true);
        pesquisando = true;
        
    }//GEN-LAST:event_jjm_jBtnPesquisarActionPerformed

    private void jjm_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jjm_jTxtVendedor, jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco);

    Util.habilitar(true, jjm_jBtnConfirmar, jjm_jBtnCancelar);
    Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

    jjm_jTxtVendedor.setText("");
    jjm_jTxtNome.setText("");
    jjm_jTxtEmail.setText("");
    jjm_jTxtTelefone.setText("");
    jjm_jFmtDatadecadastro.setText("");
    jjm_jTxtSalario.setText("");
    jjm_jTxtEndereco.setText("");
      jjm_jTxtVendedor.grabFocus();
        incluir = true;
    }//GEN-LAST:event_jjm_jBtnIncluirActionPerformed

    private void jjm_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnAlterarActionPerformed
 Util.habilitar(true, jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco);

    Util.habilitar(true, jjm_jBtnConfirmar, jjm_jBtnCancelar);
    Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);
        jjm_jTxtNome.grabFocus();
        incluir = false;
    }//GEN-LAST:event_jjm_jBtnAlterarActionPerformed

    private void jjm_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnExcluirActionPerformed
    
     if (Util.perguntar("Deseja Excluir?") == true) {
            VendedorDAO vendedorDAO = new VendedorDAO();
            vendedorDAO.delete(viewBean());
                Util.limpar(jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco);  
        }
    }//GEN-LAST:event_jjm_jBtnExcluirActionPerformed

    private void jjm_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnConfirmarActionPerformed
       VendedorDAO vendedorDAO = new VendedorDAO();
        if (incluir == true) {
            vendedorDAO.insert(viewBean());
        } else {
            vendedorDAO.update(viewBean());
        }
        Util.habilitar(false, jjm_jTxtVendedor, jjm_jTxtNome, jjm_jTxtEmail,
            jjm_jTxtTelefone, jjm_jFmtDatadecadastro, jjm_jTxtSalario, jjm_jTxtEndereco,
            jjm_jBtnConfirmar, jjm_jBtnCancelar);
    
    Util.habilitar(true, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar, jjm_jBtnIncluir);

    }//GEN-LAST:event_jjm_jBtnConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jjm_JDlgVendedor dialog = new Jjm_JDlgVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jjm_jBtnAlterar;
    private javax.swing.JButton jjm_jBtnCancelar;
    private javax.swing.JButton jjm_jBtnConfirmar;
    private javax.swing.JButton jjm_jBtnExcluir;
    private javax.swing.JButton jjm_jBtnIncluir;
    private javax.swing.JButton jjm_jBtnPesquisar;
    private javax.swing.JFormattedTextField jjm_jFmtDatadecadastro;
    private javax.swing.JLabel jjm_jLblDataDeCadrastro;
    private javax.swing.JLabel jjm_jLblEmail;
    private javax.swing.JLabel jjm_jLblEndereco;
    private javax.swing.JLabel jjm_jLblNome;
    private javax.swing.JLabel jjm_jLblSalario;
    private javax.swing.JLabel jjm_jLblTelefone;
    private javax.swing.JLabel jjm_jLblVendedor;
    private javax.swing.JTextField jjm_jTxtEmail;
    private javax.swing.JTextField jjm_jTxtEndereco;
    private javax.swing.JTextField jjm_jTxtNome;
    private javax.swing.JTextField jjm_jTxtSalario;
    private javax.swing.JTextField jjm_jTxtTelefone;
    private javax.swing.JTextField jjm_jTxtVendedor;
    // End of variables declaration//GEN-END:variables
}
