/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jjm_view;

<<<<<<< HEAD
import tools.Util;

=======
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
/**
 *
 * @author user
 */
public class Jjm_JDlgVenda_Produto extends javax.swing.JDialog {

    /**
     * Creates new form Jjm_JDlgVenda_Produto
     */
    public Jjm_JDlgVenda_Produto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
<<<<<<< HEAD
        setTitle("Cadastro de Venda_Produto");

        Util.habilitar(false, jjm_jTxtVenda_Produto, jjm_jTxtVenda, jjm_jTxtProduto,
                   jjm_jTxtQuantidade, jjm_jTxtValor_unitario);

    
    Util.habilitar(false, jjm_jBtnConfirmar, jjm_jBtnCancelar);

    
    Util.habilitar(true, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

=======
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjm_jTxtVenda_Produto = new javax.swing.JTextField();
        jjm_jLblVenda = new javax.swing.JLabel();
        jjm_jTxtVenda = new javax.swing.JTextField();
        jjm_jLblProduto = new javax.swing.JLabel();
        jjm_jTxtProduto = new javax.swing.JTextField();
        jjm_jLblQuantidade = new javax.swing.JLabel();
        jjm_jTxtQuantidade = new javax.swing.JTextField();
        jjm_jLblValor_unitario = new javax.swing.JLabel();
        jjm_jTxtValor_unitario = new javax.swing.JTextField();
        jjm_jLblVenda_produto = new javax.swing.JLabel();
        jjm_jBtnAlterar = new javax.swing.JButton();
        jjm_jBtnExcluir = new javax.swing.JButton();
        jjm_jBtnConfirmar = new javax.swing.JButton();
        jjm_jBtnCancelar = new javax.swing.JButton();
        jjm_jBtnPesquisar = new javax.swing.JButton();
        jjm_jBtnIncluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jjm_jLblVenda.setText("Venda");

        jjm_jLblProduto.setText("Produto");

        jjm_jLblQuantidade.setText("Quantidade");

        jjm_jLblValor_unitario.setText("Valor_Unitario");

        jjm_jLblVenda_produto.setText("Venda_Produto");

        jjm_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jjm_jBtnAlterar.setText("Alterar");
        jjm_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnAlterarActionPerformed(evt);
            }
        });

        jjm_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jjm_jBtnExcluir.setText("Excluir");
        jjm_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnExcluirActionPerformed(evt);
            }
        });

        jjm_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jjm_jBtnConfirmar.setText("Confirmar");
        jjm_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnConfirmarActionPerformed(evt);
            }
        });

        jjm_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jjm_jBtnCancelar.setText("Cancelar");
        jjm_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnCancelarActionPerformed(evt);
            }
        });

        jjm_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jjm_jBtnPesquisar.setText("Pesquisar");
        jjm_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnPesquisarActionPerformed(evt);
            }
        });

        jjm_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jjm_jBtnIncluir.setText("Incluir");
        jjm_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnIncluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jLblVenda_produto)
                        .addGap(61, 61, 61)
                        .addComponent(jjm_jLblVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jTxtVenda_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jjm_jTxtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jLblProduto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jjm_jTxtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jLblQuantidade)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jjm_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jjm_jTxtValor_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jLblValor_unitario))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jBtnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jjm_jBtnConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jBtnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jjm_jBtnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jjm_jBtnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jjm_jBtnAlterar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblVenda_produto)
                    .addComponent(jjm_jLblVenda)
                    .addComponent(jjm_jLblProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtVenda_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblQuantidade)
                    .addComponent(jjm_jLblValor_unitario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtValor_unitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnIncluir)
                    .addComponent(jjm_jBtnConfirmar)
                    .addComponent(jjm_jBtnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnExcluir)
                    .addComponent(jjm_jBtnPesquisar)
                    .addComponent(jjm_jBtnAlterar))
                .addGap(0, 96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jjm_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnAlterarActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
          Util.habilitar(true, jjm_jTxtVenda_Produto, jjm_jTxtVenda, jjm_jTxtProduto,
                   jjm_jTxtQuantidade, jjm_jTxtValor_unitario,
                   jjm_jBtnConfirmar, jjm_jBtnCancelar);
    Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

=======
        
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
    }//GEN-LAST:event_jjm_jBtnAlterarActionPerformed

    private void jjm_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnExcluirActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
         Util.perguntar("Deseja excluir o registro?");
=======
        
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa

    }//GEN-LAST:event_jjm_jBtnExcluirActionPerformed

    private void jjm_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnConfirmarActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
         Util.habilitar(false, jjm_jTxtVenda_Produto, jjm_jTxtVenda, jjm_jTxtProduto,
                    jjm_jTxtQuantidade, jjm_jTxtValor_unitario,
                    jjm_jBtnConfirmar, jjm_jBtnCancelar);
    Util.habilitar(true, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

=======
        
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
    }//GEN-LAST:event_jjm_jBtnConfirmarActionPerformed

    private void jjm_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnCancelarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jjm_jBtnCancelarActionPerformed

    private void jjm_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
         Util.mensagem("Pesquisa não implementada.");
=======
      
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
    }//GEN-LAST:event_jjm_jBtnPesquisarActionPerformed

    private void jjm_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnIncluirActionPerformed
        // TODO add your handling code here:
<<<<<<< HEAD
   

    Util.habilitar(true, jjm_jTxtVenda_Produto, jjm_jTxtVenda, jjm_jTxtProduto,
                   jjm_jTxtQuantidade, jjm_jTxtValor_unitario,
                   jjm_jBtnConfirmar, jjm_jBtnCancelar);

    Util.habilitar(false, jjm_jBtnIncluir, jjm_jBtnAlterar, jjm_jBtnExcluir, jjm_jBtnPesquisar);

=======
      
>>>>>>> ecca9fa7b02041200b23e91c4dcc5efda9b102aa
    }//GEN-LAST:event_jjm_jBtnIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVenda_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVenda_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVenda_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgVenda_Produto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jjm_JDlgVenda_Produto dialog = new Jjm_JDlgVenda_Produto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jjm_jBtnAlterar;
    private javax.swing.JButton jjm_jBtnCancelar;
    private javax.swing.JButton jjm_jBtnConfirmar;
    private javax.swing.JButton jjm_jBtnExcluir;
    private javax.swing.JButton jjm_jBtnIncluir;
    private javax.swing.JButton jjm_jBtnPesquisar;
    private javax.swing.JLabel jjm_jLblProduto;
    private javax.swing.JLabel jjm_jLblQuantidade;
    private javax.swing.JLabel jjm_jLblValor_unitario;
    private javax.swing.JLabel jjm_jLblVenda;
    private javax.swing.JLabel jjm_jLblVenda_produto;
    private javax.swing.JTextField jjm_jTxtProduto;
    private javax.swing.JTextField jjm_jTxtQuantidade;
    private javax.swing.JTextField jjm_jTxtValor_unitario;
    private javax.swing.JTextField jjm_jTxtVenda;
    private javax.swing.JTextField jjm_jTxtVenda_Produto;
    // End of variables declaration//GEN-END:variables
}
