/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jjm_view;

import tools.Util;

/**
 *
 * @author user
 */
public class Jjm_JDlgUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form Jjm_JDlgUsuarios
     */
    public Jjm_JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuarios");
        setLocationRelativeTo(null);
        Util.habilitar(false, jjm_jTxtApelido,jjm_jTxtCodigo,jjm_jTxtNome,jjm_PwdSenha,jjm_jChbAtivo,jjm_jFmtDataDenascimento,jjm_jFmtCpf,jjm_jCboNivel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jjm_jLblNivel = new javax.swing.JLabel();
        jjm_jLblCodigo = new javax.swing.JLabel();
        jjm_jTxtCodigo = new javax.swing.JTextField();
        jjm_jLblNome = new javax.swing.JLabel();
        jjm_jTxtNome = new javax.swing.JTextField();
        jjm_jLblApelido = new javax.swing.JLabel();
        jjm_jTxtApelido = new javax.swing.JTextField();
        jjm_jLblDateNasc = new javax.swing.JLabel();
        jjm_jFmtDataDenascimento = new javax.swing.JFormattedTextField();
        jjm_jLblCpf = new javax.swing.JLabel();
        jjm_jFmtCpf = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jjm_PwdSenha = new javax.swing.JPasswordField();
        jjm_jLblNivel1 = new javax.swing.JLabel();
        jjm_jCboNivel = new javax.swing.JComboBox<>();
        jjm_jChbAtivo = new javax.swing.JCheckBox();
        jjm_jBtnIncluir = new javax.swing.JButton();
        jjm_jBtnAlterar = new javax.swing.JButton();
        jjm_jBtnExcluir = new javax.swing.JButton();
        jjm_jBtnConfirmar = new javax.swing.JButton();
        jjm_jBtnCancelar = new javax.swing.JButton();
        jjm_jBtnPesquisar = new javax.swing.JButton();

        jjm_jLblNivel.setText("Nível");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jjm_jLblCodigo.setText("Codigo:");

        jjm_jTxtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jTxtCodigoActionPerformed(evt);
            }
        });

        jjm_jLblNome.setText("Nome:");

        jjm_jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jTxtNomeActionPerformed(evt);
            }
        });

        jjm_jLblApelido.setText("Apelido:");

        jjm_jTxtApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jTxtApelidoActionPerformed(evt);
            }
        });

        jjm_jLblDateNasc.setText("Data de Nascimento");

        jjm_jLblCpf.setText("Cpf:");

        jLabel1.setText("Senha");

        jjm_jLblNivel1.setText("Nível");

        jjm_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Convidado", "Usuarios", " " }));
        jjm_jCboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jCboNivelActionPerformed(evt);
            }
        });

        jjm_jChbAtivo.setText("Ativo");
        jjm_jChbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jChbAtivoActionPerformed(evt);
            }
        });

        jjm_jBtnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jjm_jBtnIncluir.setText("Incluir");
        jjm_jBtnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnIncluirActionPerformed(evt);
            }
        });

        jjm_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jjm_jBtnAlterar.setText("Alterar");
        jjm_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnAlterarActionPerformed(evt);
            }
        });

        jjm_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jjm_jBtnExcluir.setText("Excluir");
        jjm_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnExcluirActionPerformed(evt);
            }
        });

        jjm_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jjm_jBtnConfirmar.setText("Confirmar");
        jjm_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnConfirmarActionPerformed(evt);
            }
        });

        jjm_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jjm_jBtnCancelar.setText("Cancelar");
        jjm_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnCancelarActionPerformed(evt);
            }
        });

        jjm_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jjm_jBtnPesquisar.setText("Pesquisar");
        jjm_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jjm_jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jjm_jFmtDataDenascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jjm_jFmtCpf))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jjm_jLblCodigo)
                                .addGap(85, 85, 85)
                                .addComponent(jjm_jLblNome)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jjm_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jjm_jLblApelido))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel1))
                                    .addComponent(jjm_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjm_PwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jjm_jLblDateNasc)
                                .addGap(18, 18, 18)
                                .addComponent(jjm_jLblCpf))
                            .addComponent(jjm_jLblNivel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jjm_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jjm_jChbAtivo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jjm_jBtnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jjm_jBtnPesquisar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jjm_jBtnIncluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jjm_jBtnConfirmar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jjm_jBtnCancelar)
                                    .addComponent(jjm_jBtnAlterar))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jjm_jLblCodigo)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jjm_jLblNome)
                            .addComponent(jjm_jLblApelido))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jLblDateNasc)
                    .addComponent(jjm_jLblCpf)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jFmtDataDenascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_PwdSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jjm_jLblNivel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjm_jChbAtivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnIncluir)
                    .addComponent(jjm_jBtnConfirmar)
                    .addComponent(jjm_jBtnAlterar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jjm_jBtnExcluir)
                    .addComponent(jjm_jBtnPesquisar)
                    .addComponent(jjm_jBtnCancelar))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jjm_jTxtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jTxtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jTxtCodigoActionPerformed

    private void jjm_jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jTxtNomeActionPerformed

    private void jjm_jTxtApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jTxtApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jTxtApelidoActionPerformed

    private void jjm_jCboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jCboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jCboNivelActionPerformed

    private void jjm_jChbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jChbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jjm_jChbAtivoActionPerformed

    private void jjm_jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,jjm_jTxtApelido,jjm_jTxtCodigo,jjm_jTxtNome,jjm_PwdSenha,jjm_jChbAtivo,jjm_jFmtDataDenascimento,jjm_jFmtCpf,jjm_jCboNivel,jjm_jBtnConfirmar,jjm_jBtnCancelar );
         Util.habilitar(false, jjm_jBtnAlterar,jjm_jBtnExcluir,jjm_jBtnPesquisar,jjm_jBtnIncluir);

Util.limpar(jjm_jTxtCodigo,jjm_jTxtNome,jjm_jTxtApelido);
    }//GEN-LAST:event_jjm_jBtnIncluirActionPerformed

    private void jjm_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnAlterarActionPerformed
        Util.habilitar(true,jjm_jTxtApelido,jjm_jTxtCodigo,jjm_jTxtNome,jjm_PwdSenha,jjm_jChbAtivo,jjm_jFmtDataDenascimento,jjm_jFmtCpf,jjm_jCboNivel,jjm_jBtnConfirmar,jjm_jBtnCancelar );
         Util.habilitar(false, jjm_jBtnAlterar,jjm_jBtnExcluir,jjm_jBtnPesquisar,jjm_jBtnIncluir);

    }//GEN-LAST:event_jjm_jBtnAlterarActionPerformed

    private void jjm_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnExcluirActionPerformed
        Util.perguntar("Deseja excluir o registro?");

    }//GEN-LAST:event_jjm_jBtnExcluirActionPerformed

    private void jjm_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnConfirmarActionPerformed
        Util.habilitar(false,jjm_jTxtApelido,jjm_jTxtCodigo,jjm_jTxtNome,jjm_PwdSenha,jjm_jChbAtivo,jjm_jFmtDataDenascimento,jjm_jFmtCpf,jjm_jCboNivel,jjm_jBtnConfirmar,jjm_jBtnCancelar );
         Util.habilitar(true, jjm_jBtnAlterar,jjm_jBtnExcluir,jjm_jBtnPesquisar,jjm_jBtnIncluir);
    }//GEN-LAST:event_jjm_jBtnConfirmarActionPerformed

    private void jjm_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnCancelarActionPerformed
         Util.habilitar(false,jjm_jTxtApelido,jjm_jTxtCodigo,jjm_jTxtNome,jjm_PwdSenha,jjm_jChbAtivo,jjm_jFmtDataDenascimento,jjm_jFmtCpf,jjm_jCboNivel,jjm_jBtnConfirmar,jjm_jBtnCancelar );
         Util.habilitar(true, jjm_jBtnAlterar,jjm_jBtnExcluir,jjm_jBtnPesquisar,jjm_jBtnIncluir);
    }//GEN-LAST:event_jjm_jBtnCancelarActionPerformed

    private void jjm_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jjm_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        /* String id = JOptionPane.showInputDialog(null, "Entre com o código ?");
        int codigo = Integer.valueOf(id);
        Jjm_UsuarioDAO usuariosDao = new Jjm_UsuarioDAO();
        Jjm_Usuario usuarios = (Jjm_Usuario) usuariosDao.list(codigo);
        if (usuarios == null) {
            JOptionPane.showMessageDialog(null, "Codigo nao existente");
        } else {
            jjm_jTxtCodigo.setText(id);
            jjm_jTxtNome.setText(usuarios.getjjm_Nome());
            jjm_jTxtApelido.setText(usuarios.getjjm_Apelido());
            jjm_jFmtCpf.setText(usuarios.getjjm_Cpf());
            jjm_jFmtDataDenascimento.setText(usuarios.getjjm_Senha());
            jCboNivel.setSelectedIndex(usuarios.getjjm_Nivel());

            if (usuarios.getjjm_Ativo().equals("S")) {
                jjm_jChbAtivo.setSelected(true);
            } else {
                jjm_jChbAtivo.setSelected(false);
            }
        }*/
          Util.mensagem("Nao Implementado.");
    }//GEN-LAST:event_jjm_jBtnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jjm_JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Jjm_JDlgUsuarios dialog = new Jjm_JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jjm_PwdSenha;
    private javax.swing.JButton jjm_jBtnAlterar;
    private javax.swing.JButton jjm_jBtnCancelar;
    private javax.swing.JButton jjm_jBtnConfirmar;
    private javax.swing.JButton jjm_jBtnExcluir;
    private javax.swing.JButton jjm_jBtnIncluir;
    private javax.swing.JButton jjm_jBtnPesquisar;
    private javax.swing.JComboBox<String> jjm_jCboNivel;
    private javax.swing.JCheckBox jjm_jChbAtivo;
    private javax.swing.JFormattedTextField jjm_jFmtCpf;
    private javax.swing.JFormattedTextField jjm_jFmtDataDenascimento;
    private javax.swing.JLabel jjm_jLblApelido;
    private javax.swing.JLabel jjm_jLblCodigo;
    private javax.swing.JLabel jjm_jLblCpf;
    private javax.swing.JLabel jjm_jLblDateNasc;
    private javax.swing.JLabel jjm_jLblNivel;
    private javax.swing.JLabel jjm_jLblNivel1;
    private javax.swing.JLabel jjm_jLblNome;
    private javax.swing.JTextField jjm_jTxtApelido;
    private javax.swing.JTextField jjm_jTxtCodigo;
    private javax.swing.JTextField jjm_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
