package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JjmClientes generated by hbm2java
 */
@Entity
@Table(name="jjm_clientes"
    ,catalog="db_juan_gomez"
)
public class JjmClientes  implements java.io.Serializable {


     private Integer jjmIdCliente;
     private String jjmNome;
     private String jjmEmail;
     private String jjmSexo;
     private String jjmTelefone;
     private String jjmEndereco;
     private Date jjmDataNasc;
     private String jjmFormaPagamento;
     private String jjmRg;
     private String jjmTipoCliente;
     private String jjmCep;
     private String jjmEstado;
     private String jjmCidade;
     private Date jjmDataUltimaCompra;
     private String jjmBairro;
   

    public JjmClientes() {
    }

    public JjmClientes(String jjmNome, String jjmEmail, String jjmSexo, String jjmTelefone, String jjmEndereco, Date jjmDataNasc, String jjmFormaPagamento, String jjmRg, String jjmTipoCliente, String jjmCep, String jjmEstado, String jjmCidade, Date jjmDataUltimaCompra, String jjmBairro, Set jjmVendas) {
       this.jjmNome = jjmNome;
       this.jjmEmail = jjmEmail;
       this.jjmSexo = jjmSexo;
       this.jjmTelefone = jjmTelefone;
       this.jjmEndereco = jjmEndereco;
       this.jjmDataNasc = jjmDataNasc;
       this.jjmFormaPagamento = jjmFormaPagamento;
       this.jjmRg = jjmRg;
       this.jjmTipoCliente = jjmTipoCliente;
       this.jjmCep = jjmCep;
       this.jjmEstado = jjmEstado;
       this.jjmCidade = jjmCidade;
       this.jjmDataUltimaCompra = jjmDataUltimaCompra;
       this.jjmBairro = jjmBairro;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jjm_id_cliente", unique=true, nullable=false)
    public Integer getJjmIdCliente() {
        return this.jjmIdCliente;
    }
    
    public void setJjmIdCliente(Integer jjmIdCliente) {
        this.jjmIdCliente = jjmIdCliente;
    }

    
    @Column(name="jjm_nome", length=150)
    public String getJjmNome() {
        return this.jjmNome;
    }
    
    public void setJjmNome(String jjmNome) {
        this.jjmNome = jjmNome;
    }

    
    @Column(name="jjm_email", length=150)
    public String getJjmEmail() {
        return this.jjmEmail;
    }
    
    public void setJjmEmail(String jjmEmail) {
        this.jjmEmail = jjmEmail;
    }

    
    @Column(name="jjm_sexo", length=1)
    public String getJjmSexo() {
        return this.jjmSexo;
    }
    
    public void setJjmSexo(String jjmSexo) {
        this.jjmSexo = jjmSexo;
    }

    
    @Column(name="jjm_telefone", length=16)
    public String getJjmTelefone() {
        return this.jjmTelefone;
    }
    
    public void setJjmTelefone(String jjmTelefone) {
        this.jjmTelefone = jjmTelefone;
    }

    
    @Column(name="jjm_endereco", length=150)
    public String getJjmEndereco() {
        return this.jjmEndereco;
    }
    
    public void setJjmEndereco(String jjmEndereco) {
        this.jjmEndereco = jjmEndereco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_dataNasc", length=10)
    public Date getJjmDataNasc() {
        return this.jjmDataNasc;
    }
    
    public void setJjmDataNasc(Date jjmDataNasc) {
        this.jjmDataNasc = jjmDataNasc;
    }

    
    @Column(name="jjm_forma_pagamento", length=150)
    public String getJjmFormaPagamento() {
        return this.jjmFormaPagamento;
    }
    
    public void setJjmFormaPagamento(String jjmFormaPagamento) {
        this.jjmFormaPagamento = jjmFormaPagamento;
    }

    
    @Column(name="jjm_rg", length=11)
    public String getJjmRg() {
        return this.jjmRg;
    }
    
    public void setJjmRg(String jjmRg) {
        this.jjmRg = jjmRg;
    }

    
    @Column(name="jjm_tipo_cliente", length=150)
    public String getJjmTipoCliente() {
        return this.jjmTipoCliente;
    }
    
    public void setJjmTipoCliente(String jjmTipoCliente) {
        this.jjmTipoCliente = jjmTipoCliente;
    }

    
    @Column(name="jjm_cep", length=9)
    public String getJjmCep() {
        return this.jjmCep;
    }
    
    public void setJjmCep(String jjmCep) {
        this.jjmCep = jjmCep;
    }

    
    @Column(name="jjm_estado", length=2)
    public String getJjmEstado() {
        return this.jjmEstado;
    }
    
    public void setJjmEstado(String jjmEstado) {
        this.jjmEstado = jjmEstado;
    }

    
    @Column(name="jjm_cidade", length=150)
    public String getJjmCidade() {
        return this.jjmCidade;
    }
    
    public void setJjmCidade(String jjmCidade) {
        this.jjmCidade = jjmCidade;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_data_ultima_compra", length=10)
    public Date getJjmDataUltimaCompra() {
        return this.jjmDataUltimaCompra;
    }
    
    public void setJjmDataUltimaCompra(Date jjmDataUltimaCompra) {
        this.jjmDataUltimaCompra = jjmDataUltimaCompra;
    }

    
    @Column(name="jjm_bairro", length=55)
    public String getJjmBairro() {
        return this.jjmBairro;
    }
    
    public void setJjmBairro(String jjmBairro) {
        this.jjmBairro = jjmBairro;
    }






}


