package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JjmProdutos generated by hbm2java
 */
@Entity
@Table(name="jjm_produtos"
    ,catalog="db_juan_gomez"
)
public class JjmProdutos  implements java.io.Serializable {


     private int jjmIdProduto;
     private String jjmNome;
     private String jjmDescricao;
     private double jjmPreco;
     private Date jjmDataCadastro;
     private String jjmMarca;
     private String jjmCategoria;

    public JjmProdutos() {
    }

    public JjmProdutos(String jjmNome, String jjmDescricao, double jjmPreco, Date jjmDataCadastro, String jjmMarca, String jjmCategoria, Set jjmVendaProdutoses) {
       this.jjmNome = jjmNome;
       this.jjmDescricao = jjmDescricao;
       this.jjmPreco = jjmPreco;
       this.jjmDataCadastro = jjmDataCadastro;
       this.jjmMarca = jjmMarca;
       this.jjmCategoria = jjmCategoria;
  
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jjm_id_produto", unique=true, nullable=false)
    public int getJjmIdProduto() {
        return this.jjmIdProduto;
    }
    
    public void setJjmIdProduto(int jjmIdProduto) {
        this.jjmIdProduto = jjmIdProduto;
    }

    
    @Column(name="jjm_nome", length=150)
    public String getJjmNome() {
        return this.jjmNome;
    }
    
    public void setJjmNome(String jjmNome) {
        this.jjmNome = jjmNome;
    }

    
    @Column(name="jjm_descricao", length=200)
    public String getJjmDescricao() {
        return this.jjmDescricao;
    }
    
    public void setJjmDescricao(String jjmDescricao) {
        this.jjmDescricao = jjmDescricao;
    }

    
    @Column(name="jjm_preco", precision=9)
    public double getJjmPreco() {
        return this.jjmPreco;
    }
    
    public void setJjmPreco(double jjmPreco) {
        this.jjmPreco = jjmPreco;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_data_cadastro", length=10)
    public Date getJjmDataCadastro() {
        return this.jjmDataCadastro;
    }
    
    public void setJjmDataCadastro(Date jjmDataCadastro) {
        this.jjmDataCadastro = jjmDataCadastro;
    }

    
    @Column(name="jjm_marca", length=100)
public String getJjmMarca() {
        return this.jjmMarca;
    }
    
    public void setJjmMarca(String jjmMarca) {
        this.jjmMarca = jjmMarca;
    }

    
    @Column(name="jjm_categoria", length=100)
    public String getJjmCategoria() {
        return this.jjmCategoria;
    }
    
    public void setJjmCategoria(String jjmCategoria) {
        this.jjmCategoria = jjmCategoria;
    }

 @Override
    public String toString(){
        return this.jjmNome;
    }
     @Override
            public boolean equals(Object object){
        if (object instanceof JjmProdutos){
            JjmProdutos produtos = (JjmProdutos)object;
            if (this.getJjmIdProduto()== produtos.getJjmIdProduto()){
                return true;
            }
        }
         return false;
    }




}


