package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JjmUsuarios generated by hbm2java
 */
@Entity
@Table(name="jjm_usuarios"
    ,catalog="db_juan_gomez"
)
public class JjmUsuarios  implements java.io.Serializable {


     private Integer jjmIdusuarios;
     private String jjmNome;
     private String jjmApelido;
     private String jjmCpf;
     private Date jjmDataNasc;
     private String jjmSenha;
     private String jjmAtivo;
     private Integer jjmNivel;

    public JjmUsuarios() {
    }

    public JjmUsuarios(String jjmNome, String jjmApelido, String jjmCpf, Date jjmDataNasc, String jjmSenha, String jjmAtivo, Integer jjmNivel) {
       this.jjmNome = jjmNome;
       this.jjmApelido = jjmApelido;
       this.jjmCpf = jjmCpf;
       this.jjmDataNasc = jjmDataNasc;
       this.jjmSenha = jjmSenha;
       this.jjmAtivo = jjmAtivo;
       this.jjmNivel = jjmNivel;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jjm_idusuarios", unique=true, nullable=false)
    public Integer getJjmIdusuarios() {
        return this.jjmIdusuarios;
    }
    
    public void setJjmIdusuarios(Integer jjmIdusuarios) {
        this.jjmIdusuarios = jjmIdusuarios;
    }

    
    @Column(name="jjm_nome", length=150)
    public String getJjmNome() {
        return this.jjmNome;
    }
    
    public void setJjmNome(String jjmNome) {
        this.jjmNome = jjmNome;
    }

    
    @Column(name="jjm_apelido", length=150)
    public String getJjmApelido() {
        return this.jjmApelido;
    }
    
    public void setJjmApelido(String jjmApelido) {
        this.jjmApelido = jjmApelido;
    }

    
    @Column(name="jjm_cpf", length=20)
    public String getJjmCpf() {
        return this.jjmCpf;
    }
    
    public void setJjmCpf(String jjmCpf) {
        this.jjmCpf = jjmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_dataNasc", length=10)
    public Date getJjmDataNasc() {
        return this.jjmDataNasc;
    }
    
    public void setJjmDataNasc(Date jjmDataNasc) {
        this.jjmDataNasc = jjmDataNasc;
    }

    
    @Column(name="jjm_senha", length=50)
    public String getJjmSenha() {
        return this.jjmSenha;
    }
    
    public void setJjmSenha(String jjmSenha) {
        this.jjmSenha = jjmSenha;
    }

    
    @Column(name="jjm_ativo", length=1)
    public String getJjmAtivo() {
        return this.jjmAtivo;
    }
    
    public void setJjmAtivo(String jjmAtivo) {
        this.jjmAtivo = jjmAtivo;
    }

    
    @Column(name="jjm_nivel")
    public Integer getJjmNivel() {
        return this.jjmNivel;
    }
    
    public void setJjmNivel(Integer jjmNivel) {
        this.jjmNivel = jjmNivel;
    }




}


