package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JjmVendedor generated by hbm2java
 */
@Entity
@Table(name="jjm_vendedor"
    ,catalog="db_juan_gomez"
)
public class JjmVendedor  implements java.io.Serializable {


     private Integer jjmIdVendedor;
     private String jjmNome;
     private String jjmEmail;
     private String jjmTelefone;
     private Date jjmDataCadrastro;
     private BigDecimal jjmSalario;
     private String jjmEndereco;
     private Set jjmVendas = new HashSet(0);

    public JjmVendedor() {
    }

    public JjmVendedor(String jjmNome, String jjmEmail, String jjmTelefone, Date jjmDataCadrastro, BigDecimal jjmSalario, String jjmEndereco, Set jjmVendas) {
       this.jjmNome = jjmNome;
       this.jjmEmail = jjmEmail;
       this.jjmTelefone = jjmTelefone;
       this.jjmDataCadrastro = jjmDataCadrastro;
       this.jjmSalario = jjmSalario;
       this.jjmEndereco = jjmEndereco;
       this.jjmVendas = jjmVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jjm_id_vendedor", unique=true, nullable=false)
    public Integer getJjmIdVendedor() {
        return this.jjmIdVendedor;
    }
    
    public void setJjmIdVendedor(Integer jjmIdVendedor) {
        this.jjmIdVendedor = jjmIdVendedor;
    }

    
    @Column(name="jjm_nome", length=150)
    public String getJjmNome() {
        return this.jjmNome;
    }
    
    public void setJjmNome(String jjmNome) {
        this.jjmNome = jjmNome;
    }

    
    @Column(name="jjm_email", length=150)
    public String getJjmEmail() {
        return this.jjmEmail;
    }
    
    public void setJjmEmail(String jjmEmail) {
        this.jjmEmail = jjmEmail;
    }

    
    @Column(name="jjm_telefone", length=16)
    public String getJjmTelefone() {
        return this.jjmTelefone;
    }
    
    public void setJjmTelefone(String jjmTelefone) {
        this.jjmTelefone = jjmTelefone;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_data_cadrastro", length=10)
    public Date getJjmDataCadrastro() {
        return this.jjmDataCadrastro;
    }
    
    public void setJjmDataCadrastro(Date jjmDataCadrastro) {
        this.jjmDataCadrastro = jjmDataCadrastro;
    }

    
    @Column(name="jjm_salario", precision=9)
    public BigDecimal getJjmSalario() {
        return this.jjmSalario;
    }
    
    public void setJjmSalario(BigDecimal jjmSalario) {
        this.jjmSalario = jjmSalario;
    }

    
    @Column(name="jjm_endereco", length=150)
    public String getJjmEndereco() {
        return this.jjmEndereco;
    }
    
    public void setJjmEndereco(String jjmEndereco) {
        this.jjmEndereco = jjmEndereco;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="jjmVendedor")
    public Set getJjmVendas() {
        return this.jjmVendas;
    }
    
    public void setJjmVendas(Set jjmVendas) {
        this.jjmVendas = jjmVendas;
    }




}


