package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JjmVenda generated by hbm2java
 */
@Entity
@Table(name="jjm_venda"
    ,catalog="db_juan_gomez"
)
public class JjmVenda  implements java.io.Serializable {


     private int jjmIdVenda;
     private JjmClientes jjmClientes;
     private JjmVendedor jjmVendedor;
     private Date jjmDataVenda;
     private double jjmValorTotal;

    public JjmVenda() {
    }

    public JjmVenda(JjmClientes jjmClientes, JjmVendedor jjmVendedor, Date jjmDataVenda, double jjmValorTotal, Set jjmVendaProdutoses) {
       this.jjmClientes = jjmClientes;
       this.jjmVendedor = jjmVendedor;
       this.jjmDataVenda = jjmDataVenda;
       this.jjmValorTotal = jjmValorTotal;
    }
   
     @Id

    
    @Column(name="jjm_id_venda", unique=true, nullable=false)
    public int getJjmIdVenda() {
        return this.jjmIdVenda;
    }
    
    public void setJjmIdVenda(int jjmIdVenda) {
        this.jjmIdVenda = jjmIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jjm_fk_cliente")
    public JjmClientes getJjmClientes() {
        return this.jjmClientes;
    }
    
    public void setJjmClientes(JjmClientes jjmClientes) {
        this.jjmClientes = jjmClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jjm_fk_vendedor")
    public JjmVendedor getJjmVendedor() {
        return this.jjmVendedor;
    }
    
    public void setJjmVendedor(JjmVendedor jjmVendedor) {
        this.jjmVendedor = jjmVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jjm_data_venda", length=10)
    public Date getJjmDataVenda() {
        return this.jjmDataVenda;
    }
    
    public void setJjmDataVenda(Date jjmDataVenda) {
        this.jjmDataVenda = jjmDataVenda;
    }

    
    @Column(name="jjm_valor_total", precision=10)
    public double getJjmValorTotal() {
        return this.jjmValorTotal;
    }
    
    public void setJjmValorTotal(double jjmValorTotal) {
        this.jjmValorTotal = jjmValorTotal;
    }






}


