package bean;
// Generated 06/10/2025 20:15:00 by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JjmVendaProdutos generated by hbm2java
 */
@Entity
@Table(name="jjm_venda_produtos"
    ,catalog="db_juan_gomez"
)
public class JjmVendaProdutos  implements java.io.Serializable {


     private int jjmIdVendaProduto;
     private JjmProdutos jjmProdutos;
     private JjmVenda jjmVenda;
     private int jjmQuantidade;
     private double jjmValorUnitario;

    public JjmVendaProdutos() {
    }

    public JjmVendaProdutos(JjmProdutos jjmProdutos, JjmVenda jjmVenda, int jjmQuantidade, double jjmValorUnitario) {
       this.jjmProdutos = jjmProdutos;
       this.jjmVenda = jjmVenda;
       this.jjmQuantidade = jjmQuantidade;
       this.jjmValorUnitario = jjmValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="jjm_id_venda_produto", unique=true, nullable=false)
    public int getJjmIdVendaProduto() {
        return this.jjmIdVendaProduto;
    }
    
    public void setJjmIdVendaProduto(int jjmIdVendaProduto) {
        this.jjmIdVendaProduto = jjmIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jjm_fk_produto")
    public JjmProdutos getJjmProdutos() {
        return this.jjmProdutos;
    }
    
    public void setJjmProdutos(JjmProdutos jjmProdutos) {
        this.jjmProdutos = jjmProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jjm_fk_id_venda")
    public JjmVenda getJjmVenda() {
        return this.jjmVenda;
    }
    
    public void setJjmVenda(JjmVenda jjmVenda) {
        this.jjmVenda = jjmVenda;
    }

    
    @Column(name="jjm_quantidade")
    public int getJjmQuantidade() {
        return this.jjmQuantidade;
    }
    
    public void setJjmQuantidade(int jjmQuantidade) {
        this.jjmQuantidade = jjmQuantidade;
    }

    
    @Column(name="jjm_valor_unitario", precision=8)
    public double getJjmValorUnitario() {
        return this.jjmValorUnitario;
    }
    
    public void setJjmValorUnitario(double jjmValorUnitario) {
        this.jjmValorUnitario = jjmValorUnitario;
    }




}


